
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - mern
  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - mongo
networks:
  mern:
    driver: bridge
volumes:
  mongo-data:
    driver: local
